# Generated by Django 6.1.1 on 2026-09-17 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('greatkar', '0002_alter_catergory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='photos/products')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('catergory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greatkar.catergory')),
            ],
        ),
    ]
