# Generated by Django 6.1.1 on 2026-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greatkar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catergory',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
